### PR TITLE
Use unoptimized layernorm kernel if pointers are not aligned

### PR DESCRIPTION
**Pull request by timmoon10**
We've encountered some problems with misaligned pointers when running with DeepSpeed. In particular, their ZeRO implementation packs parameters into flattened buffers, so a single parameter with non-nice dims can throw off the alignment of subsequent parameters. I've been able to make some progress by adapting layernorm to use an unoptimized kernel (without vectorized memory accesses) if it detects any unaligned pointers. We could also make similar changes to RMSNorm, although at a certain point I would prefer a full refactor of layernorm and RMSNorm using NVRTC.

Note that DeepSpeed would probably benefit from an option to pad parameters to some fixed alignment. I'm not too familiar, but I suspect it might affect the kernels selected by cuBLAS, cuDNN, and other libraries.

### CODE REVIEW

**Comment by timmoon10** [comment]
One of the H100 nodes is being fluky and `te-ci/L0_paddle_unittest--H100_1GPU` passed when I reran the job. See pipeline 11892432.

**Review by ptrendx — APPROVED** [review]

**Pull request merged**
