### PR TITLE
fix NVTE_UB_WITH_MPI read

### PR DESCRIPTION
**Pull request by erhoo82**
# Description

Fix reading `NVTE_UB_WITH_MPI` env var.

## Type of change

- [ ] Documentation change (change only to the documentation, either a fix or a new content)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Infra/Build change
- [ ] Code refractor

## Changes

- Fix reading str to reading as bool

# Checklist:

- [ ] I have read and followed the [contributing guidelines](https://github.com/NVIDIA/TransformerEngine/blob/main/CONTRIBUTING.rst)
- [ ] The functionality is complete
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by ksivaman — APPROVED** [review]
LGTM

**Review by denera — APPROVED** [review]
LGTM. I'm guessing you're trying to handle the case where `NVTE_UB_WITH_MPI=0` in the environment?

**Comment by erhoo82** [comment]
> LGTM. I'm guessing you're trying to handle the case where `NVTE_UB_WITH_MPI=0` in the environment?

Yes, correct. We plan to use NCCL bootstrapping from nemo 24.09 container.

**Pull request merged**
