### PR TITLE
[PyTorch] Move FusedAdam/FusedSGD and necessary kernels from Apex to TE

### PR DESCRIPTION
**Pull request by yaox12**
# Description

This PR moves `FusedAdam`/`FusedSGD` and necessary `multi_tensor_*` kernels from Apex to TE, as well as the tests.

## Type of change

- [ ] Documentation change (change only to the documentation, either a fix or a new content)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Changes

Please list the changes introduced in this PR:

- Move `multi_tensor_*` kernels
- Move `FusedAdam`
- Move `FusedSGD`
- Move tests

# Checklist:

- [ ] I have read and followed the [contributing guidelines](https://github.com/NVIDIA/TransformerEngine/blob/main/CONTRIBUTING.rst)
- [ ] The functionality is complete
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by yaox12** [comment]
@timmoon10 Can I get this PR merged if it looks good to you? It's sufficient to be a drop-in replacement of Apex.FusedAdam in MCore. Other features to be migrated or implemented will come in separate PRs.

**Review by timmoon10 — APPROVED** [review]
LGTM, I confirm this is mostly copy-pasted from Apex with some minor formatting changes.

**Pull request merged**
