### PR TITLE
[common/PyTorch] Add cuDNN SWA (left, 0) + padding + bottom right causal

### PR DESCRIPTION
**Pull request by cyanguwa**
# Description

This PR adds SWA (left, 0) support to the `FusedAttention` backend for {`bshd`, `sbhd`, `thd`} formats and {`no_mask`, `causal`, `causal_bottom_right`, `padding`, `padding_causal`, `padding_causal_bottom_right`} masks.

Previously, the support was only for SWA (left, 0) with {`bshd`, `sbhd`} formats, and {`no_mask`, `causal`} mask.

This PR requires cudnn-frontend 1.9.

## Type of change

- [ ] Documentation change (change only to the documentation, either a fix or a new content)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Infra/Build change
- [ ] Code refractor

## Changes

Please list the changes introduced in this PR:

- Add cuDNN SWA (left, 0) + padding + bottom right causal

# Checklist:

- [x] I have read and followed the [contributing guidelines](https://github.com/NVIDIA/TransformerEngine/blob/main/CONTRIBUTING.rst)
- [x] The functionality is complete
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by cyanguwa** [comment]
This PR currently passes all test with cudnn-frontend 1.9 develop branch. Will run full CI when 1.9 is released.

**Review by zlsh80826 — APPROVED** [review]

**Pull request merged**
