### PR TITLE
[Paddle] Fix device memory leak

### PR DESCRIPTION
**Pull request by Tom-Zheng**
# Description

Fix device memory leak caused by pp forward hook.

## Type of change

- [ ] Documentation change (change only to the documentation, either a fix or a new content)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Infra/Build change
- [ ] Code refractor

## Changes

- Avoid register PP fwd begin hook when CUDA graph is not enabled or PP is not enabled.

# Checklist:

- [ ] I have read and followed the [contributing guidelines](https://github.com/NVIDIA/TransformerEngine/blob/main/CONTRIBUTING.rst)
- [ ] The functionality is complete
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Tom-Zheng** [comment]
Add @eee4017 to review

**Comment by Tom-Zheng** [comment]
@zlsh80826  Would you please trigger pipeline?

**Comment by Tom-Zheng** [comment]
@zlsh80826 Would you please trigger pipeline?

**Review by timmoon10 — APPROVED** [review]

**Pull request merged**
