### PR TITLE
TP-RS overlap with send/recv ring-exchange

### PR DESCRIPTION
**Pull request by erhoo82**
- Support tensor-parallel reduce-scatter (TP-RS) overlap using send/recv ring-exchange
- Support local reduction of TP-RS overlap using FP8 inputs
- Enable to specify the overlap method (`pipeline` or `ring-exchange`) for each instance. A user should set the overlap method by a yaml config file.

### CODE REVIEW

**Review by timmoon10 — APPROVED** [review]
LGTM, with stylistic suggestions.

**Comment by erhoo82** [comment]
Thanks, I have reflected the suggested changes.

**Comment by erhoo82** [comment]
@timmoon10 Can you trigger the ci test?

**Comment by minitu** [comment]
@erhoo82 Do we have corresponding changes in MCore to update the TP overlap flags in their TE wrapper classes (e.g., [TELinear](https://github.com/NVIDIA/Megatron-LM/blob/e4dcc7150aff078fd31659abb91b06c6c6bbe22e/megatron/core/transformer/custom_layers/transformer_engine.py#L119))

**Comment by erhoo82** [comment]
Can we merge this PR if no issues?

**Pull request merged**
