### PR TITLE
[Paddle] Add control of RNG state

### PR DESCRIPTION
**Pull request by Tom-Zheng**
This PR allows user to control the RNG state of attention dropout and hidden dropout. Referring to [PaddleNLP](https://github.com/PaddlePaddle/PaddleNLP/blob/2aa58d83a68ccae29c2c740867e98762e608c559/paddlenlp/trainer/trainer_utils.py#L77), attention dropout uses `local_seed` and hidden dropout uses `global_seed`.

### CODE REVIEW

**Comment by Tom-Zheng** [comment]
+ @jeng1220 to take a look.

**Review by timmoon10 — APPROVED** [review]
LGTM

**Comment by Tom-Zheng** [comment]
@zlsh80826 Would you please help trigger CI?

**Pull request merged**
