### PR TITLE
Slightly more explicit error message for invalid FP8 GEMM dims

### PR DESCRIPTION
**Pull request by timmoon10**
Closes https://github.com/NVIDIA/TransformerEngine/issues/688.

### CODE REVIEW

**Review by ksivaman — APPROVED** [review]
LGTM

**Comment by lucifer1004** [comment]
The new error message is much clearer. One thing: the previous check does not require the tensor dim to be 2, but now it becomes mandatory.

**Comment by lucifer1004** [comment]
It means I have to reshape my arrays into 2D to use FP8?

**Pull request merged**
