### PR TITLE
[JAX] Splitting `csrc/modules.cpp` by category

### PR DESCRIPTION
**Pull request by phu0ngng**
This PR splits the `csrc/modules.cpp` into multiple files, grouped by category.
No code changes, in reality, just re-organizing work.

## Type of change

- [ ] Documentation change (change only to the documentation, either a fix or a new content)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] I have read and followed the [contributing guidelines](https://github.com/NVIDIA/TransformerEngine/blob/main/CONTRIBUTING.rst)
- [x] The functionality is complete
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by denera — APPROVED** [review]
LGTM!

Let's coordinate with @ksivaman on whether to merge this before or after PR #877. One or the other would need to be rebased to account for build changes.

**Comment by ksivaman** [comment]
@phu0ngng I think we're ready to resolve conflicts and merge this!

**Pull request merged**
