### PR TITLE
Remove the autocast_variable from TF-TE

### PR DESCRIPTION
**Pull request by kaixih**
We are not recommended to use the `autocast_variable` from keras, which is an internal API. So, this PR gets rid of it.

cc. @trevor-m @pjannaty

### CODE REVIEW

**Review by timmoon10 — APPROVED** [review]
LGTM

**Review by ksivaman — APPROVED** [review]

**Review by timmoon10 — CHANGES_REQUESTED** [review]
Looks like we seeing segfaults in the tests.

**Comment by kaixih** [comment]
How can I access the logs about the segfault? I clicked the "Details" link of those failed tests, but then I couldn't find the log that contains the error.

**Comment by kaixih** [comment]
I just ran the tests on H100, A100, V100 and didn't see the segfault. ಠ_ಠ

**Comment by timmoon10** [comment]
It's a bit hidden: Details > Upload Log > Log

**Review by timmoon10 — APPROVED** [review]

**Pull request merged**
