### PR TITLE
[Paddle] Add sequence parallel

### PR DESCRIPTION
**Pull request by Tom-Zheng**

### CODE REVIEW

**Comment by Tom-Zheng** [comment]
Will be ready after TransformerLayer UT and GPT convergence test is done.

**Comment by Tom-Zheng** [comment]
@jeng1220 It is ready now.

**Comment by jeng1220** [comment]
LGTM
@timmoon10 ,
Could you please merge this PR if everything looks good?
Other PRs are based on this one.

**Review by ksivaman — APPROVED** [review]
Looks good, CI is clean

**Pull request merged**
