### PR TITLE
[JAX] Splitting cpp_extensions.py

### PR DESCRIPTION
**Pull request by phu0ngng**
# Description

- This PR Splits the `jax/cpp_extensions.py` into multiple files by category. New files are now in the `jax/cpp_extensions/` dir.
- All cpp extension functions are now imported as a part of the `tex` module.
- Renaming `mlp.py` and `fused_attn.py` to `layernorm_mlp.py` and `attention.py`. (I may move these module files into a new `modules` folder to be consistent with TE/PyTorch).

There is no change in the implementation. 

## Type of change

- [ ] Documentation change (change only to the documentation, either a fix or a new content)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] I have read and followed the [contributing guidelines](https://github.com/NVIDIA/TransformerEngine/blob/main/CONTRIBUTING.rst)
- [x] The functionality is complete
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by denera** [comment]
Is this a duplicate with #883?

**Comment by phu0ngng** [comment]
> Is this a duplicate with #883?

Hi, This is not a duplicate of #883. I apologize for the very confusing names. I updated the name of the old PR to make it more clear. I also rebased so that the changes in the old PR are not included in the PR. Happy review ^^!

**Comment by denera** [comment]
@phu0ngng The PR looks good, but unit tests have import failures. Could you fix those? We can re-run CI and merge afterward. Thanks!!

**Review by denera — CHANGES_REQUESTED** [review]
The PR looks good, but unit tests have import failures. Could you fix those? We can re-run CI and merge afterward. Thanks!!

**Review by denera — APPROVED** [review]
LGTM!

**Pull request merged**
