### PR TITLE
Fused rope compute in fp32

### PR DESCRIPTION
**Pull request by ksivaman**
Also fixes the following compilation error for cuda12.1 and below:
```
error: ambiguous "?" operation: second operand of type "float" can be converted to third operand type "const transformer_engine::bf16", and vice versa
```

### CODE REVIEW

**Comment by ptrendx** [comment]
Fixes #638

**Review by ptrendx — APPROVED** [review]

**Comment by ptrendx** [comment]
Considering I wrote this, we should have somebody else review and approve as well though :-P. @timmoon10 could you take a look?
@ksivaman Could you do a quick benchmark of this? I assume that the perf impact to the kernels should be pretty minimal and I see that as a needed change, but we should check that.
Also, @yaox12 FYI, this PR fixes a compilation error with CUDA 12.1 and changes the internal computation from the I/O type to FP32.

**Comment by ksivaman** [comment]
Across a shmoo of rotary percentages, hidden sizes, and sequence lengths, and head dimension lengths, the forward and backward speeds of the newer kernel is roughly the same with some variance (+- 0-4us). There doesn't seem to be any perf slowdown.

**Pull request merged**
