### PR TITLE
Fix QKV dtype in the bwd of FP8+CP

### PR DESCRIPTION
**Pull request by xrennvidia**
# Description

Fix the QKV dtype in the bwd of FP8+CP.

## Type of change

- [ ] Documentation change (change only to the documentation, either a fix or a new content)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Infra/Build change
- [ ] Code refractor

## Changes

Please list the changes introduced in this PR:

- Change A
- Change B

# Checklist:

- [x] I have read and followed the [contributing guidelines](https://github.com/NVIDIA/TransformerEngine/blob/main/CONTRIBUTING.rst)
- [ ] The functionality is complete
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by cyanguwa** [comment]
Can we test both the E4M3 and HYBRID fp8 recipes please? Can we add that to the unit tests?

**Comment by xrennvidia** [comment]
> Can we test both the E4M3 and HYBRID fp8 recipes please? Can we add that to the unit tests?

This is easy, we just need to change a flag of FP8 recipe, but I think this probably will not add anything additional to the test. I am comparing the results of CP>1 vs. CP=1. E4M2 and HYBRID share the same code, and I think HYBRID test can cover everything of E4M3. For example the bug in this PR is for HYBRID only, it should work for E4M3 because fwd and bwd dtype are same.

Maybe I am misunderstanding your point. In your mind, do you have anything special of E4M3 that cannot be covered by HYBRID test?

**Review by cyanguwa — APPROVED** [review]
LGTM

**Pull request merged**
