### PR TITLE
Use 2hd layout for context parallelism

### PR DESCRIPTION
**Pull request by xrennvidia**
# Description

Use bshd_bs2hd or sbhd_sb2hd layout for context parallelism.

Fixes # (issue)

## Type of change

- [ ] Documentation change (change only to the documentation, either a fix or a new content)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Infra/Build change
- [x] Code refractor

## Changes

Please list the changes introduced in this PR:

- Change A
- Change B

# Checklist:

- [x] I have read and followed the [contributing guidelines](https://github.com/NVIDIA/TransformerEngine/blob/main/CONTRIBUTING.rst)
- [ ] The functionality is complete
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by cyanguwa — COMMENTED** [review]
@xrennvidia could you please populate the PR description and add some unit tests as well?

I'm a little confused about why we want to switch from `hd_hd_hd` to `hd_2hd`. Is there some performance benefit? Thanks.

**Comment by xrennvidia** [comment]
> @xrennvidia could you please populate the PR description and add some unit tests as well?
> 
> I'm a little confused about why we want to switch from `hd_hd_hd` to `hd_2hd`. Is there some performance benefit? Thanks.

PR description is fixed. This does not need new unit tests because this PR does not add new features.

The main motivation is to [fix here](https://github.com/NVIDIA/TransformerEngine/pull/993/files#diff-0af6d715a51b3efcebd6067805b5d17b64d25ef84399e256bade01a602ce4192L1156-R1173).

Previously, we have `sbhd_sbhd` layout for KV and KV tensor shape is [2, 2, 2//s, b, h, d]. While we try to access half sequence of KV, we need `kv[:, 0].contiguous()` which lead to an element-wise kernel.

If we change KV layout to `sb2hd`, and KV shape to [2, 2//s, b, 2, h, d]. we need `kv[0].contiguous()` to access half sequence. This does not introduce data movement in memory and will avoid the element-wise kernel.

**Comment by xrennvidia** [comment]
Close this PR as the change has been included in [PR 1012](https://github.com/NVIDIA/TransformerEngine/pull/1012).

**Comment by xrennvidia** [comment]
Close this PR as the change has been included in [PR 1012](https://github.com/NVIDIA/TransformerEngine/pull/1012).

**Pull request closed without merging**
