### PR TITLE
[PyTorch] Expose `multi_tensor_*` kernels

### PR DESCRIPTION
**Pull request by yaox12**
# Description

Expose `multi_tensor_*` kernels under `transformer_engine.pytorch.optimizers` to avoid importing `transformer_engine_torch` outside of TE.

## Type of change

- [ ] Documentation change (change only to the documentation, either a fix or a new content)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

# Checklist:

- [x] I have read and followed the [contributing guidelines](https://github.com/NVIDIA/TransformerEngine/blob/main/CONTRIBUTING.rst)
- [x] The functionality is complete
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by yaox12** [comment]
Renaming `transformer_engine_extensions` to `transformer_engine_torch` makes me realize that we should avoid importing it outside of TE, so I expose these kernels to let MCore (or other framework) use them. cc @timmoon10

**Review by timmoon10 — APPROVED** [review]
This is definitely a good idea. The API for `transformer_engine_torch` is pretty unstable and it should be treated as an internal implementation. Sorry for the pain from https://github.com/NVIDIA/TransformerEngine/pull/877.

**Comment by yaox12** [comment]
@timmoon10 Please re-run the CI.

**Pull request merged**
