### PR TITLE
Fix in MHA cross attention path

### PR DESCRIPTION
**Pull request by ksivaman**
Signed-off-by: Kirthi Shankar Sivamani <ksivamani@nvidia.com>

### CODE REVIEW

**Review by ptrendx — APPROVED** [review]
LGTM

**Comment by ptrendx** [comment]
Can we add a test for that unfused case to the unittests?

**Comment by ksivaman** [comment]
@ptrendx The unit tests we have are currently for the top level APIs. This bug arises within an internal path of the `MultiHeadAttention` module using a specific set of input arguments (a path is that is unused by the top level APIs).

**Comment by ptrendx** [comment]
So why is that path even in the code then? Can't you have TransformerLayer that will call that?

**Comment by ksivaman** [comment]
> Can't you have TransformerLayer that will call that?
 
No we can't. This is because when we optionally call the MHA module a second time in `TransformerLayer` for the `decoder`/`cross-attention` path, we hardcode the argument `input_layernorm=True` in MHA (which is what we want). The issue is when the user calls the MHA module directly with `input_layernorm=False`, `attention_type="cross"`, **and** `fuse_qkv_params=False`. 

> So why is that path even in the code then?

It is a path because those individual arguments stated above are to be supported orthogonally for the use cases that we actually want in `TransformerLayer`.

**Comment by ptrendx** [comment]
Ok, makes sense. Going forward we will need the MHA layer to be the top level API, but that is obviously not in the scope of this PR.

**Pull request merged**
