### PR TITLE
Do not store input activations when not computing weight gradients

### PR DESCRIPTION
**Pull request by erhoo82**
Store the input activation for the linear layer only when to compute weight gradients.

### CODE REVIEW

**Comment by ksivaman** [comment]
@erhoo82 Could you make this fix for the other 2 APIs as well? (`LayerNormMLP`, `Linear`)

**Comment by erhoo82** [comment]
Yes, will update the PR

**Comment by erhoo82** [comment]
@ksivaman 
Updated `layer_norm_mlp`. Looks like `linear` already stores the input activation only when weight gradient computation is valid as is in the code.

https://github.com/NVIDIA/TransformerEngine/blob/main/transformer_engine/pytorch/module/linear.py#L269-L276

**Review by ksivaman — APPROVED** [review]
LGTM

**Pull request merged**
