### PR TITLE
[JAX] Move parallel encoder tests to L0 distributed test set.

### PR DESCRIPTION
**Pull request by phu0ngng**
# Description

`test_multigpu_encoder.py`, `test_multiprocessing_encoder.py`, and `test_model_parallel_encoder.py` belonged to the L0 test set thus were always executed on a single GPU node in the CI. 

This PR moved those tests into the L0 distributed test set.

## Type of change

- [ ] Documentation change (change only to the documentation, either a fix or a new content)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Infra/Build change
- [ ] Code refractor

# Checklist:

- [x] I have read and followed the [contributing guidelines](https://github.com/NVIDIA/TransformerEngine/blob/main/CONTRIBUTING.rst)
- [x] The functionality is complete
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by phu0ngng** [comment]
Pipeline #21097641

**Comment by phu0ngng** [comment]
Pipeline #21129535

**Review by ksivaman — APPROVED** [review]
LGTM

**Comment by phu0ngng** [comment]
Pipeline #129367567.

**Pull request merged**
