### PR TITLE
Add missed arguments of apply_rotary_pos_emb in MHA

### PR DESCRIPTION
**Pull request by xrennvidia**
# Description

Add missed arguments of apply_rotary_pos_emb in MHA

## Type of change

- [ ] Documentation change (change only to the documentation, either a fix or a new content)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Infra/Build change
- [ ] Code refractor

# Checklist:

- [x] I have read and followed the [contributing guidelines](https://github.com/NVIDIA/TransformerEngine/blob/main/CONTRIBUTING.rst)
- [ ] The functionality is complete
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by yaox12 — APPROVED** [review]
LGTM.

**Comment by xrennvidia** [comment]
Close as [PR 1296](https://github.com/NVIDIA/TransformerEngine/pull/1296) can address the issue of this PR.

**Review by cyanguwa — APPROVED** [review]
LGTM

**Pull request merged**
