### PR TITLE
[Paddle] Replace paddle.fluid imports with paddle.base

### PR DESCRIPTION
**Pull request by timmoon10**
Paddle 2.6.0 renamed `paddle.fluid` to `paddle.base` (see https://github.com/PaddlePaddle/Paddle/pull/56576).

### CODE REVIEW

**Comment by jeng1220** [comment]
@Wong4j ,
Please review this PR and ensure that it can run with both Paddle 2.5.2 and Paddle 2.6.0.

**Comment by Wong4j** [comment]
> @Wong4j , Please review this PR and ensure that it can run with both Paddle 2.5.2 and Paddle 2.6.0.

LGTM. 
I have checked this PR with both Paddle 2.5.2 and Paddle 2.6.0. All the UTs passed.

**Review by ksivaman — APPROVED** [review]
LGTM

**Pull request merged**
