### PR TITLE
Fix incorrect dtype in LayerNormLinear

### PR DESCRIPTION
**Pull request by timmoon10**
We've encountered a runtime error in LayerNormLinear when training LLaMa since RMSNorm is outputting to a buffer with an invalid dtype. In particular, we are not properly handling the case where the RMSNorm output is returned in bf16.

Note that LayerNormMLP handles this correctly:
https://github.com/NVIDIA/TransformerEngine/blob/f456ba19d97e2ce3a4906f631631d0d63e13040a/transformer_engine/pytorch/module/layernorm_mlp.py#L146

### CODE REVIEW

**Review by ksivaman — APPROVED** [review]
LGTM

**Comment by ptrendx** [comment]
I opened https://github.com/NVIDIA/TransformerEngine/pull/485 to fix the errors in the fused attention test.

**Review by ptrendx — APPROVED** [review]

**Pull request merged**
