### PR TITLE
Move TE/PyTorch UT to tests/pytorch/

### PR DESCRIPTION
**Pull request by jeng1220**
1. move tests/* files to tests/pytorch/
2. adjust UT paths in qa/L0_unittest/test.sh

### CODE REVIEW

**Comment by ksivaman** [comment]
Why a separate PR for this instead of combining with #53? @jeng1220 @timmoon10

**Comment by timmoon10** [comment]
> Why a separate PR for this instead of combining with #53, just curious? @jeng1220 @timmoon10

It's orthogonal to that PR and limits the amount it touches the PyTorch infrastructure.

**Comment by ksivaman** [comment]
Fair

**Review by ksivaman — APPROVED** [review]
LGTM

**Comment by jeng1220** [comment]
@ksivaman ,
I have rebased and solved the conflict to the `main`

**Pull request merged**
