### PR TITLE
Add an option to serialize test i/o to file

### PR DESCRIPTION
**Pull request by nzmora-nvidia**
* Small refactoring of the inferencing code.
* Change the default directory where generated ONNX files are stored: use the temp directory to avoid clogging the file system.
* Add an option to serialize test input/output tensors to a Polygraphy RunResults object.

### CODE REVIEW

**Comment by ksivaman** [comment]
@nzmora-nvidia Could you sign off the commits? [This guide](https://github.com/NVIDIA/TransformerEngine/blob/main/CONTRIBUTING.rst) explains how to do it.

**Comment by nzmora-nvidia** [comment]
@ksivaman signed the commit

**Comment by ksivaman** [comment]
@nzmora-nvidia Could you merge main and resolve conflicts

**Comment by nzmora-nvidia** [comment]
Due to some logistics, I'm closing this PR and opening a new one after rebasing main.

**Pull request closed without merging**
