### PR TITLE
Update README.rst to show the table in FP8 Convergence.

### PR DESCRIPTION
**Pull request by Victarry**

### CODE REVIEW

**Comment by ksivaman** [comment]
@Victarry Did you have something to add here?

**Comment by Victarry** [comment]
@ksivaman  There are some syntax errors for the table in README.

Preview before fix:  
Screenshot 2024-03-05 at 09 12 43

Preview after fix:  
Screenshot 2024-03-05 at 09 13 06

Thanks.

**Review by ksivaman — APPROVED** [review]
LGTM

**Comment by ksivaman** [comment]
Aah, thanks for catching this!

**Pull request merged**
