### PR TITLE
Fix zombie process when querying TE install path

### PR DESCRIPTION
**Pull request by timmoon10**
This is a modification of the bugfix in https://github.com/NVIDIA/TransformerEngine/pull/120, with some small changes for safety and style.

Pinging @ngoyal2707. Closes https://github.com/NVIDIA/TransformerEngine/pull/120.

### CODE REVIEW

**Comment by ngoyal2707** [comment]
Thanks, I was on slightly older version of TE, 

now we also need same fix here: https://github.com/NVIDIA/TransformerEngine/blob/main/transformer_engine/pytorch/transformer.py#L45

**Review by ksivaman — APPROVED** [review]

**Pull request merged**
