### PR TITLE
Document how to build with symbol for gdb

### PR DESCRIPTION
**Pull request by nouiz**

### CODE REVIEW

**Review by timmoon10 — COMMENTED** [review]
This seems a bit hacky. I have been refactoring the build system and I think the most CMake-y way to handle this is to set `CMAKE_BUILD_TYPE=Debug` in the environment. We could also alternatively use a TE-specific envvar like `NVTE_BUILD_DEBUG`.

**Comment by nouiz** [comment]
I search a little on the web and some projects does it like this:
1. `python setup.py build_ext --debug install`
1. ... --debug (and parse the command line to find that parameter).

1 doesn't work for unknow reason. It seems that under some condition, self.debug end up being true in that case.

I prefer parameter to env variable. More user friendly.
What do you think of just checking if `'--debug'` is in `sys.argv` and if so, set the debug Mode?

**Comment by timmoon10** [comment]
I think the command-line arg is a sensible approach. I'll include it in my upcoming fix to the build system.

**Comment by nouiz** [comment]
> I think the command-line arg is a sensible approach. I'll include it in my upcoming build system refactor.

Good. So I'm closing this and let you implement and document it.

**Pull request closed without merging**
