### PR TITLE
Fix FP32 LayerNorm ONNX export

### LINKED ISSUE #310: Export transformer_engine.pytorch.LayerNorm to ONNX gives all zero output
After exporting `transformer_engine.pytorch.LayerNorm` to ONNX, it always give tensors with correct shape but filled with 0.

Example code:
```
import torch
import onnxruntime
from transformer_engine import pytorch as te

model = te.LayerNorm(1000).cuda().eval()
x_sample = torch.randn(3000, 1000)
with torch.inference_mode():
  torch_out = model(x_sample.cuda())    # the result is correct

with torch.inference_mode():
  with te.onnx_export(True):
    torch.onnx.export(model, x_sample.cuda(), "layer_norm.onnx", dynamic_axes={"input": {0: "batch_size"}, "output": {0: "batch_size"}}, opset_version=17, input_names=["input"], output_names=["output"])

ort_session = onnxruntime.InferenceSession("layer_norm.onnx", providers=["CPUExecutionProvider"])
ort_inputs = {ort_session.get_inputs()[0].name: to_numpy(x_sample)}
ort_output = ort_session.run(None, ort_inputs)[0]
# ort_output is all zero
```

Other pytorch modules like `transformer_engine.pytorch.LayerNormLinear` gives correct results.

OS: RHEL 7
Python: 3.10.11
TransformerEngine: 0.9
Pytorch: 2.0.1+cu118
GPU: 4090

### PR DESCRIPTION
**Pull request by nzmora-nvidia**
When running inference use a fwd method that is registered with torchscript.

This bug was reported here: https://github.com/NVIDIA/TransformerEngine/issues/310
Change the export tests to cover this export flow.

Fixes #310

### CODE REVIEW

**Comment by ksivaman** [comment]
@nzmora-nvidia What are the changes to the submodule?

**Comment by nzmora-nvidia** [comment]
Sorry about that @ksivaman: a local submodule change slipped into the PR.
Removed it now and forced pushed an update.

**Comment by ksivaman** [comment]
@nzmora-nvidia The `torch.is_grad_enabled()` is always `False` inside a custom autograd function, so the correct way of doing it would be to pass it as an argument similar to how we do in the other modules. I've made that change here as well.

**Review by ksivaman — APPROVED** [review]

**Comment by nzmora-nvidia** [comment]
Got it @ksivaman - thanks!

**Comment by ksivaman** [comment]
Pipeline 8963955

**Pull request merged**
