### PR TITLE
[PyTorch] Miscellanous fixes for FP8 DPA module

### PR DESCRIPTION
**Pull request by cyanguwa**
This PR
- fixes cuDNN version extraction in unit tests due to versioning difference between cuDNN pre-9.0 and post-9.0,
- allows for better compatibility with older checkpoints (pre-TE 1.6). Since TE 1.6, `FusedAttention` has been subclassed with `TEBaseModule`, and an `_extra_state` has been added to the module's `state_dict`. `_extra_state` contains FP8 meta data, but due to the subclassing, the addition of `_extra_state` to `state_dict` happens regardless of FP8 training or F16 training. This PR allows users to load older checkpoints (which do not have `_extra_state` for `FusedAttention`), as well as save and load new checkpoints as usual (which will contain `_extra_state` for `FusedAttention`).

### CODE REVIEW

**Comment by cyanguwa** [comment]
> I looked at this further post our sync, looks like `tp_size`/`tp_group` aren't used at all at the DPA/FusedAttention level. Can we simply remove/deprecate them? @cyanguwa

We do use `tp_group_initialized` in `prepare_forward`. Also, if we don't keep track of `tp_size/tp_group`, how do we manage amax reduction for TP groups, or does `fp8.py` already handled that?

**Comment by ksivaman** [comment]
With #575, the amax reduction is handled in the `reduce_and_update_fp8_tensors` function using the `fp8_group` passed into the autocast. So we don't store the tensor parallel group to handle it separately.

**Comment by mikolajblaz** [comment]
@cyanguwa Regarding checkpoints compatibility: not requiring `_extra_state` in state dict is good, although I believe it doesn't solve the problem on the application side in case of switching from one attention implementation to another. Would such interoperability of attention layers be possible? It would require `_extra_state` to live on the same level as the default attention implementation.

**Comment by cyanguwa** [comment]
@mikolajblaz I've moved `core_attention.fused_attention._extra_state` to `core_attention._extra_state` in [b94a1ee](https://github.com/NVIDIA/TransformerEngine/pull/804/commits/b94a1ee4df8a9d0688f93e7e8989ceeb531fa8af). Let me know if you have any thoughts/comments. Thanks.

**Comment by cyanguwa** [comment]
@ksivaman could you please help take another look?

**Comment by cyanguwa** [comment]
I had some discussion with mikolajblaz offline and we decided to not pursue the move from `core_attention.fused_attention._extra_state` to `core_attention._extra_state`. The possible solutions all look unclean and may not even guarantee the loading of checkpoints is correct. This is because PyTorch relies heavily on the module structure and `FusedAttention` is currently a submodule of `DotProductAttention`, so it's very hard to manipulate `state_dict()/load_state_dict()` calls to get around this hierarchical structure. Will consider this another time. 

https://github.com/pytorch/pytorch/blob/74b7c56517f97c5d813620da9a479417a564e8b4/torch/nn/modules/module.py#L2164

**Review by ptrendx — APPROVED** [review]
LGTM

**Review by ksivaman — APPROVED** [review]
LGTM

**Pull request merged**
