### PR TITLE
[PyTorch] Reduce size of sanity tests

### PR DESCRIPTION
**Pull request by timmoon10**
We've been seeing some OOM errors in `tests/pytorch/test_sanity.py` when running CI on an L40. It seems excessive to run a full 126M model with all the different permutations, especially since we also test these modules in `test_numerics.py` and `test_fused_attn.py`. This PR changes most of the tests use a small configuration, with only a few cases using the full 126M config.

Somewhat related: https://github.com/NVIDIA/TransformerEngine/pull/503.

### CODE REVIEW

**Review by cyanguwa — APPROVED** [review]
LGTM. Can merge after CI passes. Cheers!

**Comment by timmoon10** [comment]
Pipeline 11911964

**Pull request merged**
