### PR TITLE
Simplify dev installation guide.

### PR DESCRIPTION
**Pull request by nouiz**

### CODE REVIEW

**Comment by ksivaman** [comment]
I think it's a good idea to bundle this with #156 since that would require another change/simplification in the guide

**Comment by nouiz** [comment]
I would merge this PR now.
The other is an issue and nobody is working on it.
I took a quick look and I don't think setuptools give us what we need to trivially implement it. So this will need investigation on how to do that correctly (or hack it by parsing the command line ourself)

**Review by timmoon10 — APPROVED** [review]

**Comment by ksivaman** [comment]
Could you sign-off your commit? @nouiz

**Comment by timmoon10** [comment]
I'd be happy merging as-is since this is orthogonal to #156. After signing the commit though.

**Comment by nouiz** [comment]
Signed.

**Review by ksivaman — COMMENTED** [review]
LGTM

**Comment by ptrendx** [comment]
Hmmm, shouldn't we tell people to install `stable` though instead of `main`?

**Comment by nouiz** [comment]
This was in the development version section.
The default should use the wheel.

**Comment by nouiz** [comment]
I see what you mean. But this PR doesn't introduce the issue you raise. It was already there as it was already installing from the main branch.

There is others issues:
- We should link to the full installation doc and not duplicate all of it.
- The full installation doc doesn't talk about the FW.

This new PR try to clean that up: 
https://github.com/NVIDIA/TransformerEngine/pull/159

**Pull request merged**
