### PR TITLE
[Common] Remove CheckTensor if the workspace is empty in cast_transpose_fused

### PR DESCRIPTION
**Pull request by phu0ngng**
# Description

In JAX, we call `dbias_cast_transpose` and `dact_dbias_cast_transpose` with empty tensors to get the workspace size before calling the actual functions. So this fix is needed.

## Type of change

- [ ] Documentation change (change only to the documentation, either a fix or a new content)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Infra/Build change
- [ ] Code refractor

## Changes

- [x] I have read and followed the [contributing guidelines](https://github.com/NVIDIA/TransformerEngine/blob/main/CONTRIBUTING.rst)
- [ ] The functionality is complete
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by ksivaman — APPROVED** [review]
LGTM, fixes:
```
RuntimeError: /opt/transformerengine/transformer_engine/common/transformer_engine.cpp:39 in function CheckInputTensor: Assertion failed: t.data.dptr != nullptr. Input cast_transpose_fused_input is not allocated!
```

**Comment by phu0ngng** [comment]
\te-ci jax

**Comment by phu0ngng** [comment]
Hi, 
I added another small change that fixed the issue:
```
FAILED tests/jax/test_single_gpu_mnist.py::TestMNIST::test_te_bf16 - ValueError: The repository for mnist contains custom code which must be executed to correctly ...
```
This issue is not related to the previous issue, but without this fix the CI won't come back clean so I decided to push it to the same PR.

**Pull request merged**
