### PR TITLE
[PyTorch] Linear: fix computation for wgrad if sequence_parallel=True

### PR DESCRIPTION
**Pull request by Marks101**
This PR adresses the issue described in #530 by using `gather_along_first_dim` instead of `gather_along_last_dim` as in other places (eg `LayerNormLinear`). The reasoning is that I did not come up with an elegant solution for a correct `gather_along_last_dim` that does not use additional transposes or explicit calls to `torch.cat` which make interleaving with the dgrad computation difficult. But I would be happy to hear other ideas or suggestions.

All in all, the code might be easier if the transpose of the input tensor is always done in the backward pass. Right now the case fp8 and sequence_parallel=False still used the fused cast in the forward pass. Happy to hear your opinion on that as well. Furthermore `gather_along_last_dim` probably should be removed now.

One further question: Is there any reason that `fp8_gemm` does not have an layout argument like `gemm` does?

### CODE REVIEW

**Review by timmoon10 — APPROVED** [review]
Thanks for the bug report and fix! I reproduce the bug in https://github.com/NVIDIA/TransformerEngine/issues/530 and I see that [`torch.distributed.all_gather_into_tensor`](https://pytorch.org/docs/stable/distributed.html#torch.distributed.all_gather_into_tensor) just checks that the buffers have the right number of entries and then passes directly into `ncclAllgather`. I've completely removed `gather_along_last_dim` and we can re-add it with a correct implementation when needed.

**Comment by Marks101** [comment]
Whops, I screwed up the line length and that triggered L0_pytorch_lint to fail. Sorry about that. I fixed it.

Furthermore, the CI shows lots of errors in `test_onnx_export.py`: `RuntimeError: Detected that you are using FX to torch.jit.trace a dynamo-optimized function. This is not supported at the moment`. I am not sure how this is connected to my changes.

**Pull request merged**
