### PR TITLE
[C/PyTorch] Add THD MQA/GQA

### PR DESCRIPTION
**Pull request by cyanguwa**
# Description

This PR adds THD MQA/GQA support for FusedAttention sub-backend 1 for cuDNN 9.6+. #1260 focuses on Jax, while this PR focuses on PyTorch. Can merge in any order.

## Type of change

- [ ] Documentation change (change only to the documentation, either a fix or a new content)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Infra/Build change
- [ ] Code refractor

## Changes

Please list the changes introduced in this PR:

- Add THD MQA/GQA support and tests

# Checklist:

- [x] I have read and followed the [contributing guidelines](https://github.com/NVIDIA/TransformerEngine/blob/main/CONTRIBUTING.rst)
- [x] The functionality is complete
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by zlsh80826 — APPROVED** [review]
LGTM!

**Comment by Marks101** [comment]
We are actually very interessted in THD + fused attention + GQA/MQA. This requires [CUDNN](https://docs.nvidia.com/deeplearning/cudnn/latest/) 9.6 which was not released yet, do I understand that correctly?

**Comment by cyanguwa** [comment]
> We are actually very interessted in THD + fused attention + GQA/MQA. This requires [CUDNN](https://docs.nvidia.com/deeplearning/cudnn/latest/) 9.6 which was not released yet, do I understand that correctly?

Yes, that's correct. It should come out in a month or so.

**Pull request merged**
