### PR TITLE
[PyTorch] Stop storing fused weight tensor in linear modules

### PR DESCRIPTION
**Pull request by timmoon10**
We've encountered excessive memory usage with FSDP-like workflows because `Linear` and `LayerNormLinear` sometimes store a tensor for fused weights. The weight params may be manipulated externally, e.g. to deallocate them or make them views into an all-gather buffer, but the modules hold on to the original buffers and prevent any memory savings. This PR updates the `_noop_cat` utility function so that it no longer requires the full output tensor, but can figure things out by inspecting the pointers and strides. There is one functional difference: `Linear` and `LayerNormLinear` no longer make any attempt to readjust the params if they are not contiguous, but will just concatenate as needed. Besides, if FSDP is misconfigured it will just wipe out the existing buffers and create new misaligned weights in every forward pass, so there's no hope that TE can repair the situation.

This is related to https://github.com/NVIDIA/TransformerEngine/pull/570, which removed the fused weight tensors in cases without split weight params.

### CODE REVIEW

**Comment by timmoon10** [comment]
This PR has exposed a bug in our numeric tests. Previously, `Linear` and `LayerNormLinear` would hold onto the fused weight tensor and would "repair" the params by making sure they were views of that tensor. However, most of the tests in `test_numerics.py` initialize TE modules like:
```python
block = te.Linear(...).to(dtype=dtype).cuda()
```
Since the module was initialized in FP32, it would "repair" FP16/BF16 params by turning them back to FP32. No wonder we were able to achieve such tight numerical tolerances.

**Comment by timmoon10** [comment]
The failed test is unrelated (`test_layernorm_accuracy`) and it passed after rerunning.

**Comment by deepakn94** [comment]
Anything holding up this being merged?

**Pull request merged**
