### PR TITLE
[PyTorch] FP8 fixes

### PR DESCRIPTION
**Pull request by ksivaman**
- [x] Refactor FP8 utilities into classes similar to TE/JAX.
- [x] Fix checkpointing bugs by storing full global state, including buffer and variables.
- [x] Fix segfault when moving forward amax reduction to beginning of next autocast.
- [x] Make `fp8_autocast` modular and simple.

### CODE REVIEW

**Comment by ksivaman** [comment]
Tested with:
- [x] DP
- [x] TP/SP
- [x] PP
- [x] Previous checkpoints
- [x] SAR/full activation recompute

**Review by timmoon10 — APPROVED** [review]
As we've discussed, the only functional change I see is including some FP8 context state in the checkpoints.

Having a giant singleton class feels a little wonky, but I think it is somewhat better than having a bunch of global variables. Implementation is easier, even if it makes calling the functions a bit more verbose.

**Pull request merged**
