### PR TITLE
[Paddle] Fix issues

### PR DESCRIPTION
**Pull request by Wong4j**
1. Fix the shape of softmax_aux - [b, h, s, s] for max512, [b, h, s, 1] for arbitrary seqlen.
2. Register rng_state as inplace tensor.

### CODE REVIEW

**Comment by jeng1220** [comment]
LGTM

**Comment by jeng1220** [comment]
@cyanguwa ,
All tests passed.
Could you please merge this branch if everything looks good?

**Review by cyanguwa — APPROVED** [review]
Looks good to me. Thanks.

**Pull request merged**
