### PR TITLE
Deprecate unused APIs

### PR DESCRIPTION
**Pull request by ksivaman**

### CODE REVIEW

**Review by timmoon10 — CHANGES_REQUESTED** [review]
We should only display the warning in the case the user tries to use these APIs. Also, I think exceptions are more appropriate than warnings since we are not going to be following the behavior expected by users.

**Comment by ksivaman** [comment]
@timmoon10 I agree that the exception makes more sense for when a `weight` and `bias` are passed in to forward, but I've left the `skip_weight_param_allocation` passed in as just a warning, which I think is better.

**Review by timmoon10 — APPROVED** [review]
LGTM. My last nitpick is that we could mention in the warning message that `skip_weight_param_allocation` is not doing anything.

**Comment by ksivaman** [comment]
Pipeline 8976176

**Pull request merged**
