### PR TITLE
[JAX] Use relative idx to ScaledUpperTriangMaskedSoftmaxFwdPrimitive

### PR DESCRIPTION
**Pull request by mingxu1067**
* Use relative idx to ScaledUpperTriangMaskedSoftmaxFwdPrimitive for supporting mulitple batching dimensions.

### CODE REVIEW

**Comment by nouiz** [comment]
Is this a bugfix? Should you add a test?

**Comment by mingxu1067** [comment]
> Is this a bugfix? Should you add a test?

Yes it is a bugfix, only shows up when enabling `vamp`. We have not implemented relevant UTs. Will schedule time to do so.
We verified this fix locally with Paxml + PP.

**Comment by mingxu1067** [comment]
Those failures of UTs about FusedAttn are fixed by [PR-521](https://github.com/NVIDIA/TransformerEngine/pull/521)

**Review by denera — APPROVED** [review]

**Comment by nouiz** [comment]
At a high level, it looks good. CI failures. I let Ming review the details.

**Comment by mingxu1067** [comment]
@denera @nouiz all tests are passed, kindly help to review and merge. Thanks.

**Pull request merged**
