### PR TITLE
[Paddle] Add FP8 support for nn Layers

### PR DESCRIPTION
**Pull request by Tom-Zheng**
Add FP8 support for the following layers:
- Linear
- LayerNorm
- LayerNormLinear
- LayerNormMLP

Add MNIST FP8 example.

### CODE REVIEW

**Comment by Tom-Zheng** [comment]
Hi @timmoon10 , would you please review this PR?

cc: @jeng1220 , @Wong4j

**Comment by Tom-Zheng** [comment]
+ @timmoon10 @jeng1220  to take a look

**Comment by Tom-Zheng** [comment]
@timmoon10  I have made some changes after discussed with @jeng1220 . Also, we would like to refactor `fp8.py`, by putting the global variables like `_FP8_ENABLED` into a `class FP8State`. Please check [this commit](https://github.com/Tom-Zheng/TransformerEngine/commit/95e367a749a958f052aeddd0b9acfc0064d3b404#diff-6125905a1e3f99c20152e75dc9ef0b0274c072fb5c0215a5565e364b0b2c8f75). Do you accept this change?

**Review by timmoon10 — APPROVED** [review]
LGTM. The deviations from the PyTorch impl, like making `FP8TensorMeta` a pure Python class or storing the global FP8 status in a singleton `FP8State` class, are reasonable and actually good ideas to adopt in the PyTorch impl.

**Comment by Tom-Zheng** [comment]
@ksivaman Hi, would you please merge it?

**Comment by jeng1220** [comment]
@ksivaman,
The CI was passed. Could you please approve the PR and merge code?

**Pull request merged**
