### PR TITLE
Fix types for forward attention for JAX.

### PR DESCRIPTION
**Pull request by cheshire**
Fix types for forward attention for JAX.

Bias and seed can both be None, type checking is failed otherwise.

### CODE REVIEW

**Comment by cheshire** [comment]
Force-pushed a signed commit. Is this working now?

**Comment by nouiz** [comment]
The sign off worked. I'll let the other merge.

**Review by ksivaman — APPROVED** [review]
LGTM

**Comment by cheshire** [comment]
Is this merged automatically?

**Comment by ksivaman** [comment]
We will merge it once the CI is complete!

**Pull request merged**
