### PR TITLE
[JAX] Enhance JAX unit tests

### PR DESCRIPTION
**Pull request by zlsh80826**
This PR does the following changes:
1. Add `layernorm_fp8_dot` unit tests
2. Add `test_softmax.py` for testing the softmax primitives
3. Extend the softmax primitives max seqlen to 16384, which was introduced in https://github.com/NVIDIA/TransformerEngine/pull/652
4. Refactor `test_layer.py` and add the coverage of the following arguments
    a. dropout, dropout_dim
    b. self_attn_mask, self_attn_bias
    c. layernorm_eps, 
    d. use_bias
    e. RoPE + GQA
5. Move common fixtures to conftest.py

### CODE REVIEW

**Comment by zlsh80826** [comment]
Hi @denera and @mingxu1067 , could you help review this PR this week? 
This PR added many unit tests especially for TransformerLayer, there are many PRs with large changes are comming, we should make sure those PRs are under the latest and strictly unit tests.

**Review by denera — APPROVED** [review]
LGTM, we can merge once conflicts are resolved.

**Pull request merged**
