### PR TITLE
[UB] Adding configurable timeout for userbuffer and improving error reporting for potential hangs

### PR DESCRIPTION
**Pull request by shamisp**
This PR is replacement for #741 based on recent changes in the code.

This PR addresses the following issues:
* Adding configurable user buffer timeout instead of hardcoded
* Adding CE hang detector
* Improving error reporting for easier triage 
* Removing unused code and clearing up warnings

### CODE REVIEW

**Review by nv-akorzh — APPROVED** [review]
looks good to me, go ahead

**Review by ksivaman — APPROVED** [review]

**Pull request merged**
