### PR TITLE
[PyTorch] Use dummy amax for Float8Tensor cast

### PR DESCRIPTION
**Pull request by ksivaman**

### CODE REVIEW

**Review by timmoon10 — CHANGES_REQUESTED** [review]
Right now, any change to the values in `Float8Tensor` will update the `amax_history` in `fp8_meta`. This is necessary to automatically update the amax after in-place operations (e.g. the optimizer step) and it makes it easier to reason about `fp8_meta` (`Float8Tensor` treats the contents of `fp8_meta` as ground-truth). This happens in `Float8Tensor.to_float8`:
https://github.com/NVIDIA/TransformerEngine/blob/b8eea8aaa94bb566c3a12384eda064bda8ac4fd7/transformer_engine/pytorch/float8_tensor.py#L105
It also happens in `Float8Tensor.__torch_dispatch__` with in-place operations:
https://github.com/NVIDIA/TransformerEngine/blob/b8eea8aaa94bb566c3a12384eda064bda8ac4fd7/transformer_engine/pytorch/float8_tensor.py#L621

This PR changes the behavior so `to_float8` ignores the `amax_history` in `fp8_meta`. I see some possibilities:
- We treat `fp8_meta` differently betwen `to_float8` and `__torch_dispatch__`. This is confusing.
- We change `__torch_dispatch__` so it also ignores the `amax_history` in `fp8_meta`. This means we no longer fuse the amax with the FP8 cast, but have to externally call an amax kernel after each in-place operation.
- If there is some localized bug when calling `to_float8`, we could pass in a dummy amax there instead of modifying `Float8Tensor`.

We should do the third one if possible. As far as I'm aware, the only place we call `to_float8` is at:
https://github.com/NVIDIA/TransformerEngine/blob/b8eea8aaa94bb566c3a12384eda064bda8ac4fd7/transformer_engine/pytorch/module/base.py#L790

If we have to change `Float8Tensor`, I'd prefer if we reverted this branch and deleted these lines instead:
https://github.com/NVIDIA/TransformerEngine/blob/b8eea8aaa94bb566c3a12384eda064bda8ac4fd7/transformer_engine/pytorch/float8_tensor.py#L104-L105
This makes it more obvious that `Float8Tensor` is ignoring the `amax_history` in `fp8_meta`. We also need to figure out and document our decision regarding `__torch_dispatch__`.

**Review by timmoon10 — APPROVED** [review]
This is much nicer than the previous approach. I'm not quite comfortable that the initial weight amax will never be included in the amax history. But I suppose it's a subtle point that only affects the first step and I'll approve if it makes https://github.com/NVIDIA/TransformerEngine/pull/575 cleaner.

**Comment by ksivaman** [comment]
For reference, this also resolves the inconsistency in amax histories between weights and activations/grads, where the initial amax is included only in the weight history.

**Pull request merged**
