### PR TITLE
Remove redundant AR for SP case

### PR DESCRIPTION
**Pull request by ksivaman**
When using sequence-parallel, it is necessary to reduce amax across the tensor parallel group. Currently we handle this by reducing once across the `fp8_group` and then again across TP group if SP is used. This PR changes that to a single AR across `fp8_group` and forces `reduce_amax` in the recipe to be `True` if SP is used with FP8.

### CODE REVIEW

**Comment by timmoon10** [comment]
If I understand correctly, we now require `fp8_group` to be configured specially if sequence parallelism is enabled? In particular:
| Sequence parallelism | `fp8_group` |
|----|----|
| No | Data-parallel group |
| Yes | Data-parallel + tensor-parallel group |

**Comment by ksivaman** [comment]
Correct, if sequence parallel is used, the TP group must be included in `fp8_group`, either directly or as a subset of a larger distributed group as you mention.

**Review by timmoon10 — APPROVED** [review]
LGTM. We may also want to update the documentation at https://github.com/NVIDIA/TransformerEngine/blob/main/docs/examples/advanced_optimizations.ipynb so users understand that they have to configure different process groups for the spatial-parallel case.

**Pull request merged**
