### PR TITLE
Import framework submodules lazily

### PR DESCRIPTION
**Pull request by timmoon10**
# Description

Whenever a user calls `import transformer_engine`, we attempt to import all framework submodules (`transformer_engine.pytorch`, etc) within try-catch statements. However, this can suppress important errors and make debugging tricky. A more sophisticated approach is to [import the submodules lazily](https://docs.python.org/3/library/importlib.html#implementing-lazy-imports), i.e. only import a module the first time it is used. For example, if running with a PyTorch build of TE:

```python
import transformer_engine as te
te.pytorch.__file__  # Imports transformer_engine.pytorch
te.jax.__file__      # Imports transformer_engine.jax, fails, and throws import error
```

## Type of change

- [ ] Documentation change (change only to the documentation, either a fix or a new content)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Changes

Please list the changes introduced in this PR:

- Load framework modules lazily

# Checklist:

- [x] I have read and followed the [contributing guidelines](https://github.com/NVIDIA/TransformerEngine/blob/main/CONTRIBUTING.rst)
- [x] The functionality is complete
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by ksivaman — APPROVED** [review]
LGTM

**Review by ksivaman — CHANGES_REQUESTED** [review]
Actually I've had a slight change of mind. Maybe we need a more foolproof solution since this might just kick the can down the road for some of the linker/loader errors we've been observing? @timmoon10

**Comment by timmoon10** [comment]
The goal of this PR isn't to fix any existing bugs, just to make debugging easier by not hiding error messages. I don't think we can protect developers from themselves when they write buggy code.

**Comment by timmoon10** [comment]
Pylint doesn't seem to understand lazily imported modules and gives a bunch of spurious warnings. I've worked around this by only lazy-loading a module after failing to import it normally. This is uglier, but it still helps give more useful error messages.

**Review by ksivaman — APPROVED** [review]

**Review by ptrendx — APPROVED** [review]

**Comment by xwang233** [comment]
I think this PR is causing negative impact on users of TE. Previously, the code read
```python
try:
    from . import jax
except ImportError as e:
    pass
```

When a pytorch TE user doesn't have jax installed, it's fine. However, we now have
```python
try:
    from . import jax
except ImportError:
    jax = _lazy_import("transformer_engine.jax")
```
which not only hides the jax import error but also throws that in a much later and hard to understand place with more python lazy import stacks.

Are jax and paddle packages required for pytorch TE users now? If not, we should add try-catch blocks for all those framework imports.

cc @ptrendx  @jjsjann123 @tfogal

**Comment by xwang233** [comment]
Example stacktrace:
```python
E           RuntimeError: Process 0 exited with error code 10 and exception:
E           Traceback (most recent call last):
E             File "/usr/local/lib/python3.10/dist-packages/torch/testing/_internal/common_distributed.py", line 653, in run_test
E               getattr(self, test_name)()
E             File "/usr/local/lib/python3.10/dist-packages/torch/testing/_internal/common_distributed.py", line 539, in wrapper
E               fn()
E             File "/usr/local/lib/python3.10/dist-packages/torch/testing/_internal/common_utils.py", line 2756, in wrapper
E               method(*args, **kwargs)
E             File "/usr/local/lib/python3.10/dist-packages/torch/testing/_internal/common_utils.py", line 443, in instantiated_test
E               test(self, **param_kwargs)
E             File "/opt/pytorch/lightning-thunder/thunder/tests/distributed/test_ddp.py", line 332, in test_all_gather
E               actual = cfoo(a, b, process_group, async_op)
E             File "/opt/pytorch/lightning-thunder/thunder/__init__.py", line 615, in fn_
E               cache_entry, inps, pro_to_epi = get_computation_and_inputs(*args, **kwargs)
E             File "/opt/pytorch/lightning-thunder/thunder/__init__.py", line 202, in cache_info_wrapper
E               res = fn(*args, **kwargs)
E             File "/opt/pytorch/lightning-thunder/thunder/__init__.py", line 473, in get_computation_and_inputs
E               jit_results: TraceResults = interpreter(
E             File "/opt/pytorch/lightning-thunder/thunder/__init__.py", line 190, in _general_frontend
E               return thunder_general_jit(fn, args, kwargs, sharp_edges=sharp_edges, record_history=record_history)
E             File "/opt/pytorch/lightning-thunder/thunder/core/jit_ext.py", line 1524, in thunder_general_jit
E               result = jfn(*args, **kwargs)
E             File "/opt/pytorch/lightning-thunder/thunder/core/interpreter.py", line 6645, in fn_
E               runtimectx: InterpreterRuntimeCtx = InterpreterRuntimeCtx(debug_log=debug_log, record_history=record_history)
E             File "/opt/pytorch/lightning-thunder/thunder/core/interpreter.py", line 531, in __init__
E               self._original_callsite: inspect.FrameInfo = inspect.stack()[2]  # [__init__, fn_, callsite, ...]
E             File "/usr/lib/python3.10/inspect.py", line 1673, in stack
E               return getouterframes(sys._getframe(1), context)
E             File "/usr/lib/python3.10/inspect.py", line 1650, in getouterframes
E               frameinfo = (frame,) + getframeinfo(frame, context)
E             File "/usr/lib/python3.10/inspect.py", line 1624, in getframeinfo
E               lines, lnum = findsource(frame)
E             File "/usr/lib/python3.10/inspect.py", line 952, in findsource
E               module = getmodule(object, file)
E             File "/usr/lib/python3.10/inspect.py", line 869, in getmodule
E               if ismodule(module) and hasattr(module, '__file__'):
E             File "/usr/lib/python3.10/importlib/util.py", line 247, in __getattribute__
E               self.__spec__.loader.exec_module(self)
E             File "<frozen importlib._bootstrap_external>", line 883, in exec_module
E             File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
E             File "/usr/local/lib/python3.10/dist-packages/transformer_engine/jax/__init__.py", line 6, in <module>
E               from . import flax
E             File "/usr/local/lib/python3.10/dist-packages/transformer_engine/jax/flax/__init__.py", line 5, in <module>
E               from .module import DenseGeneral, LayerNorm
E             File "/usr/local/lib/python3.10/dist-packages/transformer_engine/jax/flax/module.py", line 14, in <module>
E               from flax import linen as nn
E           ModuleNotFoundError: No module named 'flax'
E
E           Process 1 exited with error code 10 and exception:
E           Traceback (most recent call last):
E             File "/usr/local/lib/python3.10/dist-packages/torch/testing/_internal/common_distributed.py", line 653, in run_test
E               getattr(self, test_name)()
E             File "/usr/local/lib/python3.10/dist-packages/torch/testing/_internal/common_distributed.py", line 539, in wrapper
E               fn()
E             File "/usr/local/lib/python3.10/dist-packages/torch/testing/_internal/common_utils.py", line 2756, in wrapper
E               method(*args, **kwargs)
E             File "/usr/local/lib/python3.10/dist-packages/torch/testing/_internal/common_utils.py", line 443, in instantiated_test
E               test(self, **param_kwargs)
E             File "/opt/pytorch/lightning-thunder/thunder/tests/distributed/test_ddp.py", line 332, in test_all_gather
E               actual = cfoo(a, b, process_group, async_op)
E             File "/opt/pytorch/lightning-thunder/thunder/__init__.py", line 615, in fn_
E               cache_entry, inps, pro_to_epi = get_computation_and_inputs(*args, **kwargs)
E             File "/opt/pytorch/lightning-thunder/thunder/__init__.py", line 202, in cache_info_wrapper
E               res = fn(*args, **kwargs)
E             File "/opt/pytorch/lightning-thunder/thunder/__init__.py", line 473, in get_computation_and_inputs
E               jit_results: TraceResults = interpreter(
E             File "/opt/pytorch/lightning-thunder/thunder/__init__.py", line 190, in _general_frontend
E               return thunder_general_jit(fn, args, kwargs, sharp_edges=sharp_edges, record_history=record_history)
E             File "/opt/pytorch/lightning-thunder/thunder/core/jit_ext.py", line 1524, in thunder_general_jit
E               result = jfn(*args, **kwargs)
E             File "/opt/pytorch/lightning-thunder/thunder/core/interpreter.py", line 6645, in fn_
E               runtimectx: InterpreterRuntimeCtx = InterpreterRuntimeCtx(debug_log=debug_log, record_history=record_history)
E             File "/opt/pytorch/lightning-thunder/thunder/core/interpreter.py", line 531, in __init__
E               self._original_callsite: inspect.FrameInfo = inspect.stack()[2]  # [__init__, fn_, callsite, ...]
E             File "/usr/lib/python3.10/inspect.py", line 1673, in stack
E               return getouterframes(sys._getframe(1), context)
E             File "/usr/lib/python3.10/inspect.py", line 1650, in getouterframes
E               frameinfo = (frame,) + getframeinfo(frame, context)
E             File "/usr/lib/python3.10/inspect.py", line 1624, in getframeinfo
E               lines, lnum = findsource(frame)
E             File "/usr/lib/python3.10/inspect.py", line 952, in findsource
E               module = getmodule(object, file)
E             File "/usr/lib/python3.10/inspect.py", line 869, in getmodule
E               if ismodule(module) and hasattr(module, '__file__'):
E             File "/usr/lib/python3.10/importlib/util.py", line 247, in __getattribute__
E               self.__spec__.loader.exec_module(self)
E             File "<frozen importlib._bootstrap_external>", line 883, in exec_module
E             File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
E             File "/usr/local/lib/python3.10/dist-packages/transformer_engine/jax/__init__.py", line 6, in <module>
E               from . import flax
E             File "/usr/local/lib/python3.10/dist-packages/transformer_engine/jax/flax/__init__.py", line 5, in <module>
E               from .module import DenseGeneral, LayerNorm
E             File "/usr/local/lib/python3.10/dist-packages/transformer_engine/jax/flax/module.py", line 14, in <module>
E               from flax import linen as nn
E           ModuleNotFoundError: No module named 'flax'

/usr/local/lib/python3.10/dist-packages/torch/testing/_internal/common_distributed.py:805: RuntimeError
```

**Comment by ptrendx** [comment]
Hmm, this seems to be because you are trying to inspect all of the modules, which tries to access their attributes here:
`if ismodule(module) and hasattr(module, '__file__'):`, which in turns initializes the module.

@DEKHTIARJonathan any suggestions, especially since we want to go with lazy loading as well for the PIP wheel effort? Also @ksivaman for visibility.

**Comment by timmoon10** [comment]
This is a messy bug:
- The old approach of putting the imports in try-catch statements suppressed useful error messages, especially for developers.
- It feels correct to me that `import transformer_engine.jax` should throw an import error if JAX is not installed.
- I don't think we can guarantee that the user has exactly one DL framework installed. I can imagine a user installing TE with PyTorch support, and at some later time installing JAX in the same Conda env.
- Thunder's jitter inspects the stack with [`inspect.stack`](https://docs.python.org/3/library/inspect.html#inspect.stack), which we don't want to modify or reimplement.

I have an initial fix at https://github.com/NVIDIA/TransformerEngine/pull/844, but this can run into the same Thunder bug if the user has multiple DL frameworks installed.

**Comment by xwang233** [comment]
> The old approach of putting the imports in try-catch statements suppressed useful error messages, especially for developers.

We can do 
```python
try:
    from . import jax
except ImportError as e:
    traceback.print_exc()
```

**Comment by DEKHTIARJonathan** [comment]
@timmoon10 @xwang233 @ptrendx can you try this branch.

Try with
- `export TE_LAZY_IMPORT_FLAVOR=1`
- `export TE_LAZY_IMPORT_FLAVOR=2`
- `export TE_LAZY_IMPORT_FLAVOR=3`

I have 3 tentative implementation, please let me know which one works best

**Pull request merged**
