### PR TITLE
Fix MultiHeadAttention GQA with input normalization

### PR DESCRIPTION
**Pull request by adhocyyf**
When use gqa with input normalization，both `key_layer` and `value_layer` inputs are not applying normalization.

### CODE REVIEW

**Comment by adhocyyf** [comment]
I recommend hide whitespace to review this pr: https://github.com/NVIDIA/TransformerEngine/pull/378/files?diff=unified&w=1

**Comment by cyanguwa** [comment]
Hi @adhocyyf,

Thanks for submitting this PR. If I understand correctly, the only component missing in our `main` is the `self.norm` for `hidden_states` when `self.attention_type == "self" and self.num_gqa_groups != self.num_attention_heads`. In that case, we're currently going through the same path as `self.attention_type == "cross"`, which does not apply normalization for `hidden_states` (hence affecting the calculation for `query_layer`, `key_layer` and `value_layer`). 

The code changes in this PR seem a little repetitive. If my understanding above is correct, would it be sufficient to just add the `self.norm` here:
https://github.com/NVIDIA/TransformerEngine/blob/3b7b7c68fc310067567956d6f63f633e2012bcec/transformer_engine/pytorch/attention.py#L1652 

            if self.attention_type == "cross":
                input_tensor = encoder_output
            else:
                hidden_states = self.norm(hidden_states)
                input_tensor = hidden_states

Thanks,
Charlene

**Comment by adhocyyf** [comment]
Hi @cyanguwa 

thanks for your suggestion，I simplified my PR

**Comment by cyanguwa** [comment]
@adhocyyf thanks for the changes. Please see the comment regarding fusing layernorm and q/kv linears in #394 .

**Comment by cyanguwa** [comment]
Closing the PR as relevant changes have been made in #434 . Thanks for your contribution!

**Pull request closed without merging**
