### PR TITLE
Change FP8 recipe defaults

### PR DESCRIPTION
**Pull request by ksivaman**
Also entails adding support for varying the amax history length across checkpoints.

### CODE REVIEW

**Review by timmoon10 — COMMENTED** [review]
Is there a reason why we truncate/pad the amax history in `set_meta_tensor`? It would be simpler if we did it in `set_extra_state` immediately after loading the checkpoint.

**Comment by ksivaman** [comment]
@timmoon10 We only know the recipe change during the `fp8_autocast` call in forward, not during checkpoint loading.

**Comment by ksivaman** [comment]
The changing of amax history length in the middle of training is still supported.
If at any execution we find that the current recipe is different than the user request recipe, we call `init_fp8_meta_tensors`. Where we truncate or pad depending on whether or not the current history length is different from the user requested one.

**Review by timmoon10 — APPROVED** [review]
LGTM. The logic is more intuitive to me now.

**Review by timmoon10 — APPROVED** [review]

**Pull request merged**
