### PR TITLE
[WIP] Specify WeightHParamsCollection of FP8 Meta.

### PR DESCRIPTION
**Pull request by mingxu1067**
In Praxis, each variables have their own `WeightHParamsCollection` to indicate if they are 

- trainable 
- needed to cast into lower precision (BF16).

By default, all non-trainable variables would be casted to BF16, which breaks FP8 training. To address, we proposed to manually specify `WeightHParamsCollection` for FP8 meta, like `DISALLOW_BFLOAT16_CONVERSION` to keep FP8 meta in FP32.

PS: this chagnes need some modification on Praxis, and not upstreamed yet.

### CODE REVIEW

**Comment by mingxu1067** [comment]
@nouiz @jeng1220  for viz.

**Comment by nouiz** [comment]
It looks good at a high level to me.
Can you make the PR to praxis yourself soon?
I suppose it will be a small and trivial one.

**Comment by ksivaman** [comment]
What's the status of this? @nouiz @mingxu1067

**Comment by mingxu1067** [comment]
@ksivaman sorry for late reply. We have an internal PR to allow support Prais to accept  custom `WeightHParamsCollections`, but it have not merged and upstreamed yet. After those changes reflect on Praix upstream, then it is good to merge this.

**Comment by mingxu1067** [comment]
Close this and follow up on #347

**Pull request closed without merging**
