### PR TITLE
Revert "[C/PyTorch] Removed MPI dependence in Userbuffers (#901)"

### PR DESCRIPTION
**Pull request by denera**
# Description

This reverts commit e706e5faac64aa7c7564bbee495f814c63c2c319.

NeMo/Mcore reported issues initializing Userbuffers in multi-node configurations after PR #901.

PR #986 fixes this issue, but also exhibits a ~2% regression in performance. 

This PR reverts PR #901. MPI-dependence removal will be brought back with PR #986 once the cause of the perf regression is identified and resolved.

## Type of change

- [ ] Documentation change (change only to the documentation, either a fix or a new content)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Infra/Build change
- [ ] Code refractor

## Changes

Please list the changes introduced in this PR:

- Reverts PR #901.

# Checklist:

- [x] I have read and followed the [contributing guidelines](https://github.com/NVIDIA/TransformerEngine/blob/main/CONTRIBUTING.rst)
- [x] The functionality is complete
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by ksivaman — APPROVED** [review]
This does complicate our wheels effort a bit since now ubuf is temporarily back to being its own package

**Review by ptrendx — CHANGES_REQUESTED** [review]
Let's not merge this yet. Once we have a better understanding of the cause for the regression then we can decide what to do with this.

**Comment by denera** [comment]
Closing because PR #986 was merged with the fix for bug introduced in PR #901.

**Pull request closed without merging**
