### PR TITLE
Enable TP-AG overlap with return_layernorm_output

### PR DESCRIPTION
**Pull request by minitu**

### CODE REVIEW

**Review by timmoon10 — APPROVED** [review]

**Comment by minitu** [comment]
@timmoon10 Rebased, please run CI again

**Comment by minitu** [comment]
Actually needs one more change

**Comment by minitu** [comment]
@timmoon10 Now ready for CI

**Review by ksivaman — APPROVED** [review]

**Comment by minitu** [comment]
Looks like it failed the RMSNorm tests:
```
FAILED ../../tests/pytorch/test_numerics.py::test_layernorm_linear_accuracy[True-RMSNorm-126m-2-dtype0]
FAILED ../../tests/pytorch/test_numerics.py::test_layernorm_linear_accuracy[False-RMSNorm-126m-2-dtype0]
```
I don't think they are related to this PR since `ub_overlap_ag` has to be turned on, which I believe is not covered by the unit tests.

**Comment by minitu** [comment]
@timmoon10 @ksivaman Any guidance regarding the failing test?

**Comment by ksivaman** [comment]
Re-runnning failed CI passes, the error is unrelated.

**Pull request merged**
