### PR TITLE
Initialize output tensors to 0 for THD (temporary)

### PR DESCRIPTION
**Pull request by cyanguwa**
# Description

This PR initializes output tensors O, dQ, dK, dV, dBias to 0 for THD format. This is a temporary fix before cuDNN 9.4 fixes it from their side.

## Type of change

- [ ] Documentation change (change only to the documentation, either a fix or a new content)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Infra/Build change
- [ ] Code refractor

## Changes

- Initializes O, dQ, dK, dV, dBias to 0 for PyTorch and Paddle
- Jax has already added equivalent memsets to solve this problem

# Checklist:

- [x] I have read and followed the [contributing guidelines](https://github.com/NVIDIA/TransformerEngine/blob/main/CONTRIBUTING.rst)
- [x] The functionality is complete
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by cyanguwa** [comment]
@xrennvidia This is the PR to zero out the pad tokens in THD sequences. Let me know if you have any comments. Thanks!

**Comment by xrennvidia** [comment]
> @xrennvidia This is the PR to zero out the pad tokens in THD sequences. Let me know if you have any comments. Thanks!

I do not understand PaddlePaddle code, so I only reviewed PyTorch code.

I think you should put `fill_(0)` of O and dQKV under BF16 code path. You have it for FP8 code path. You current code will do zeroing twice for FP8 code.

**Comment by xrennvidia** [comment]
@cyanguwa dQKV zeroing of `fused_attn_bwd` has not been fixed yet?

**Comment by cyanguwa** [comment]
@Wong4j could you please help take a look at the changes on the Paddle side? Thanks!

**Review by zlsh80826 — APPROVED** [review]
LGTM!

**Pull request merged**
