### PR TITLE
Check input dimensions for Sequence Parallel

### PR DESCRIPTION
**Pull request by ksivaman**
See #182

### CODE REVIEW

**Review by timmoon10 — APPROVED** [review]
This looks fine, but I'm not sure if it's protecting much against the error in #182. `seq_length` is optional and only helps with warming up some JITed kernels.

**Comment by ksivaman** [comment]
I agree @timmoon10. There's isn't currently a foolproof method of having this check, so just doing what we can with what we have makes sense.

**Comment by ksivaman** [comment]
I agree @timmoon10. There's isn't currently a foolproof method of having this check, so just doing what we can with what we have makes sense.

**Pull request merged**
