### PR TITLE
Fix compatibility with pyTorch 2.0

### LINKED ISSUE #601: The version v1.2 has compatibility issues with PyTorch 2.0.1, causing errors during execution.
Hello,

I encountered the following error while using version v1.2 of Transformer Engine: 

`no_torch_dynamo = lambda recursive=True: lambda f: torch._dynamo.disable(f, recursive=recursive). The error message is TypeError: disable() got an unexpected keyword argument 'recursive'.
`

My environment setup is as follows: CUDA 11.8, PyTorch 2.0.1, and Python 3.10. I am experiencing this issue specifically in the context of using MegatronLM at commit fab0bd6 for Large Language Model (LLM) training. The error occurs right at the start of the training.

Possible cause of the issue:
The `disable` function in PyTorch 2.0.1 is defined as `def disable(f)`, and the recursive parameter was introduced only in later versions starting from PyTorch 2.1.0.

### PR DESCRIPTION
**Pull request by ptrendx**
Fixes #601.

### CODE REVIEW

**Review by timmoon10 — APPROVED** [review]
LGTM

**Review by ksivaman — APPROVED** [review]
LGTM

**Comment by ptrendx** [comment]
Tested locally with 23.05 container that has pyTorch 2.0 that #601 does not trigger with this PR included.

**Pull request merged**
