### PR TITLE
Fix seq_dim in CP implementation

### PR DESCRIPTION
**Pull request by xrennvidia**
# Description

Fix a `seq_dim` bug in CP implementation.

## Type of change

- [ ] Documentation change (change only to the documentation, either a fix or a new content)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Infra/Build change
- [ ] Code refractor

## Changes

Please list the changes introduced in this PR:

- Change A
- Change B

# Checklist:

- [x] I have read and followed the [contributing guidelines](https://github.com/NVIDIA/TransformerEngine/blob/main/CONTRIBUTING.rst)
- [ ] The functionality is complete
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by ksivaman — APPROVED** [review]
LGTM

**Review by cyanguwa — APPROVED** [review]
LGTM

**Review by ksivaman — APPROVED** [review]
LGTM

**Comment by xrennvidia** [comment]
FA2 CI pipeline: 19422281
FA3 CI pipeline: 19426554
Confirmed with @timmoon10 that the two failed tests in the pipelines should not be related to the PR, so we can merge.

**Pull request merged**
