### PR TITLE
[JAX] Adapt to Flax 0.7.1

### PR DESCRIPTION
**Pull request by mingxu1067**
- ~Cast Flax collections to FrozenDict as WAR to adapt Flax 0.7.1.~
- Followed [migrate to the normal dict](https://flax.readthedocs.io/en/latest/guides/regular_dict_upgrade_guide.html) to apapt to Flax 0.7.1.
The root cause is that `FrozenDict` is removed from Flax 0.7.1, instead `module.init()` returns python built-in `dict` which has different behavior of `pop` with `FrozenDict`. FrozenDict's pop reuturns two outputs, remaining FrozenDict and popped value, but python built-in dict only returns popped value then in-place delete it in orginal object.

Meanwhile, add fully remove `FrozenDict` into TODO and will schedule time to fix internally.

Refer to #352

### CODE REVIEW

**Comment by mingxu1067** [comment]
@zlsh80826, @jeng1220, @nouiz for viz.

**Comment by zlsh80826** [comment]
Hi Ming,
There is a guide on how to [migrate to the normal dict](https://flax.readthedocs.io/en/latest/guides/regular_dict_upgrade_guide.html). I think this would be better, the changes are small.
```
 def generate_layer(layer_cls, init_rng, diff_inputs, no_diff_inputs):
     layer = layer_cls()
     variables = layer.init(init_rng, *diff_inputs, *no_diff_inputs)
-    others, params = variables.pop('params')
+    others, params = flax.core.pop(variables, 'params')
     del variables
     return layer, params, others

@@ -126,7 +126,7 @@ class TestEncoderLayer:
     def sync_params(ref, target, attrs):
         fuse_qkv = attrs.get(_KEY_OF_FUSE_QKV_PARAMS, True)

-        unfreeze_target = target.unfreeze()
+        unfreeze_target = flax.core.unfreeze(target)
         if fuse_qkv:
             unfreeze_target['attention']['qkv']['kernel'] = \
                 jnp.reshape(ref['attention']['qkv']['kernel'],
```

**Comment by mingxu1067** [comment]
> 

Thanks Reese for pointing this out, apopt this changes.

**Comment by nouiz** [comment]
Need to update the min flax version somewhere.

**Comment by mingxu1067** [comment]
> Need to update the min flax version somewhere.

Done, by adding it to `requirements.txt` in `examples/jax`.

**Comment by yhtang** [comment]
Confirming that TE's JAX tests in JAX-Toolbox is fixed now:
- https://github.com/NVIDIA/JAX-Toolbox/actions/runs/5746725690/job/15577049028
- https://github.com/NVIDIA/JAX-Toolbox/actions/runs/5746725690/job/15577048581
- https://github.com/NVIDIA/JAX-Toolbox/actions/runs/5746725690/job/15577048688
- https://github.com/NVIDIA/JAX-Toolbox/actions/runs/5746725690/job/15577048798
- https://github.com/NVIDIA/JAX-Toolbox/actions/runs/5746725690/job/15577048896

**Comment by nouiz** [comment]
Any idea why it is fixed? Should we drop this PR?

**Comment by timmoon10** [comment]
It looks like JAX-Toolbox is fetching this branch, so we should merge soon.

We should also update the Flax version in `setup.py`:
https://github.com/NVIDIA/TransformerEngine/blob/85928d0887234a64c63b220e3c09d8a7a0d01c7b/setup.py#L298

**Review by timmoon10 — APPROVED** [review]

**Pull request merged**
