### PR TITLE
Remove now useless padding as it is now down automatically.

### PR DESCRIPTION
**Pull request by nouiz**

### CODE REVIEW

**Comment by ksivaman** [comment]
@nouiz `0.4.16` was out on 18th September 2023, so with this change we're effectively supporting only 5 months of JAX releases, which seems too few

**Comment by nouiz** [comment]
> @nouiz `0.4.16` was out on 18th September 2023, so with this change we're effectively supporting only 5 months of JAX releases, which seems too few

Last summer, we where only supporting the last JAX release. That we now support 5 months is awesome!
But I think as the JAX release cycle is very fast, 5 months is too much.
I think 3 months (this is the normal JAX deprecation policy) is enough. But maybe in some cases, we won't be able to support that too.

I don't see 5 months as an issue blocking this PR. If you do, can you tell why?

**Review by ksivaman — APPROVED** [review]
LGTM

**Comment by ksivaman** [comment]
@nouiz Could you resolve the conflicts so that we can merge this?

**Comment by nouiz** [comment]
> @nouiz Could you resolve the conflicts so that we can merge this?

done

**Comment by ksivaman** [comment]
After a discussion with @nouiz, we will re-open a fresh PR.

**Pull request closed without merging**
