### PR TITLE
[PyTorch] Fix import of transformer_engine without cuda device

### PR DESCRIPTION
**Pull request by Marks101**
# Description

Hello everyone,

with #1226, a module level check for the compute capability was introduced. This raises a RuntimeError when importing transformer_engine in an environment without a CUDA device (eg checkpoint conversion, CI, ...). This PR proposes to add an additional `torch.cuda.is_available()` check

## Type of change

- [ ] Documentation change (change only to the documentation, either a fix or a new content)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Infra/Build change
- [ ] Code refractor

## Changes

Please list the changes introduced in this PR:

- Add check torch.cuda.is_available()

### CODE REVIEW

**Review by ksivaman — APPROVED** [review]
LGTM

**Comment by cyanguwa** [comment]
Superseded by #1287.  Thanks for raising this issue and providing this PR, Markus!! 😃

**Comment by Marks101** [comment]
Oh, thanks for taking a closer look. I missed the other imorts 🙈

**Pull request closed without merging**
