### PR TITLE
Implement fused kernel for FP8 scale update

### PR DESCRIPTION
**Pull request by timmoon10**
Running GPT 175B, I've found that the forward pass is often bottlenecked by GPU kernel launch overheads, especially in the forward pass. Profiling the Python code finds that ~20% of the Transformer layer forward pass is spent in `amax_and_scale_update`   (compare to 9% launching GEMM kernels). This function is called in every forward pass of `Linear`, `LayerNormLinear`, and `LayerNormMLP`, and each call involves ~10 small GPU operations. nvfuser and `torch.compile` do fuse some of the operations, leading to some improvement in GPU runtime, but the extra CPU overhead results in somewhat worse performance in the CPU-bound case.

This is an experiment with using a hand-written kernel to reduce these overheads. Alternative approaches:
- Only update scaling factors once per training step instead of once per microbatch
- Batch the scale updates for all layers together

### CODE REVIEW

**Comment by yaox12** [comment]
From my profiling, `_default_get_amax` is also not fused well. Can we follow paddle's https://github.com/NVIDIA/TransformerEngine/blob/753eed310efb1d47281565e361ebe735e97aa3c2/transformer_engine/paddle/fp8.py#L238 to fused the whole `amax_and_scale_update`?

**Comment by ptrendx** [comment]
Right, instead of writing another kernel in the framework-aware portion, let's actually add the Paddle kernel to the common part and use in both places.

**Comment by timmoon10** [comment]
One thing that'll make this tricky is that the Paddle kernel is in-place. The PyTorch kernel includes the amax history roll, so making that in-place would make the kernel much more complicated than it's worth. Perhaps we could move both kernels into `common` to standardize the APIs, even if they are not actually reused.

**Comment by timmoon10** [comment]
I've moved the fused kernel to the core C++ library and modified the PyTorch and Paddle extensions so they both use it. It turns out that making the kernel work in-place was not difficult.

**Comment by timmoon10** [comment]
The PyTorch and JAX tests as passing in pipeline 12465152 and the Paddle tests are failing due to a problem with cuDNN v9 in the upstream Paddle container. The Paddle tests pass when I use an older Paddle container in pipeline 12474691. This is ready to merge.

**Comment by ksivaman** [comment]
Have we tested e2e numerics for this change against the previous versions? @timmoon10

**Comment by timmoon10** [comment]
The tests pass, but I haven't tried full-scale training runs.

**Comment by timmoon10** [comment]
@ksivaman The numerics are tested thoroughly in https://github.com/NVIDIA/TransformerEngine/blob/7fc00c0819b3249d1abbb935719a81202d097e9d/tests/pytorch/test_recipe.py, so I think full-scale convergence runs are excessively careful.

**Comment by timmoon10** [comment]
After internal discussion with @ptrendx and @ksivaman, there is no objection to merging without review.

**Pull request merged**
