### PR TITLE
[PyTorch] MultiheadAttention: Pass cu_seqlens to apply_rotary_pos_emb

### PR DESCRIPTION
**Pull request by Marks101**
# Description

since #1066 `MultiheadAttention` accepts the parameters cu_seqlens_q and cu_seqlens_kv but these are not passed to `appy_rotary_pos_emb`. I think there it should be possible to simply pass them. Do you see any issues with that?

## Type of change

- [ ] Documentation change (change only to the documentation, either a fix or a new content)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Infra/Build change
- [ ] Code refractor

## Changes

Please list the changes introduced in this PR:

- pass cu_seqlens_q and cu_seqlens_kv to appy_rotary_pos_emb

# Checklist:

- [ ] I have read and followed the [contributing guidelines](https://github.com/NVIDIA/TransformerEngine/blob/main/CONTRIBUTING.rst)
- [ ] The functionality is complete
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by yaox12 — APPROVED** [review]
LGTM

**Review by yaox12 — CHANGES_REQUESTED** [review]
We should also pass `cp_size` and `cp_rank` to it.  https://github.com/nvidia/TransformerEngine/issues/1238

**Comment by xrennvidia** [comment]
> We should also pass `cp_size` and `cp_rank` introduced in #1238 to it.
> 
> For now, `MultiheadAttention` doesn't hold the CP group. Maybe we should add it in its `set_context_parallel_group`. cc @xrennvidia

`set_context_parallel_group` of MHA has `cp_group`, right? [refer here](https://github.com/NVIDIA/TransformerEngine/blob/main/transformer_engine/pytorch/attention.py#L8679-L8719)

**Comment by xrennvidia** [comment]
@yaox12 I think I get what you mean, I think you want something like `self.cp_group = cp_group` in the `set_context_parallel_group` of MHA. Then you can use it to get `cp_size` and `cp_rank` for `apply_rotary_pos_emb`. I think it makes sense. @Marks101 could you please add it as Xin Yao said? thanks

**Comment by yaox12** [comment]
After discussing with @xrennvidia, it's a bit complex to handle `cp_size` and `cp_rank` because right now CP can be a list of groups for cp_comm_type of “a2a+p2p”. So, @xrennvidia will submit a new PR by himself to fix the problem.

**Comment by xrennvidia** [comment]
@Marks101 please let us know if [this PR](https://github.com/NVIDIA/TransformerEngine/pull/1296) can address you problem. Thanks.

**Comment by Marks101** [comment]
Hi @xrennvidia and @yaox12,
oh yes, I missed the changes regarding CP. The new PR looks good to me. This should do the trick.
Thank you so much for processing this so quickly.

**Comment by xrennvidia** [comment]
Close as [PR 1296](https://github.com/NVIDIA/TransformerEngine/pull/1296) can address the issue of this PR.

**Pull request closed without merging**
