### PR TITLE
Fix CMakeList.txt to build as a sub-project

### PR DESCRIPTION
**Pull request by niboshi**
I encountered some issues while trying to integrate TransformerEngine as a subproject. These are the fixes.

* Replace `CMAKE_SOURCE_DIR` with `CMAKE_CURRENT_SOURCE_DIR`.
* Use `set( )` instead of `list(APPEND )`, as the latter resulted in command line like `...;-threads 4` in our build.

### CODE REVIEW

**Review by timmoon10 — CHANGES_REQUESTED** [review]
Looks good. Please sign your commit so it passes DCO and I'll run the CI.

**Comment by niboshi** [comment]
@timmoon10 Thanks. Signed my commit.

**Comment by niboshi** [comment]
I'm sorry, "Signed-off-by: " was missing in the commit message. I fixed it.

**Pull request merged**
